/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Users;

import javax.swing.JButton;

/**
 *
 * @author MI EQUIPO
 */
public class Codirector extends javax.swing.JFrame {

    /**
     * Creates new form Codirector
     */
    public Codirector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        AFormat = new javax.swing.JButton();
        PreProject = new javax.swing.JButton();
        Monographies = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Menú");
        jLabel10.setName("lblMenudir"); // NOI18N

        AFormat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AFormat.setText("Formato A");
        AFormat.setName("btnFormato"); // NOI18N

        PreProject.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PreProject.setText("Anteproyectos");
        PreProject.setName("btnAnteproyecto"); // NOI18N

        Monographies.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Monographies.setText("Monografías");
        Monographies.setName("btnMonografias"); // NOI18N

        Exit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Exit.setText("Salir");
        Exit.setName("btnExit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PreProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Monographies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AFormat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(AFormat)
                .addGap(18, 18, 18)
                .addComponent(PreProject)
                .addGap(18, 18, 18)
                .addComponent(Monographies)
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAFormat() {
        return AFormat;
    }

    public JButton getExit() {
        return Exit;
    }
    
    public JButton getMonographies() {
        return Monographies;
    }
    
    public JButton getPreProject() {
        return PreProject;
    }

    public JButton[] getButtons(){
        return new JButton[]{AFormat, Exit, Monographies, PreProject};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AFormat;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Monographies;
    private javax.swing.JButton PreProject;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
