/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Users;

import javax.swing.JButton;

/**
 *
 * @author MI EQUIPO
 */
public class JefeDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form JefeDepartamento
     */
    public JefeDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PreProjects = new javax.swing.JButton();
        AssignEvaluators = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");
        jLabel1.setName("lblMenudir"); // NOI18N

        PreProjects.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PreProjects.setText("Anteproyectos");
        PreProjects.setName("btnAnteproyecto"); // NOI18N

        AssignEvaluators.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AssignEvaluators.setText("Asignar Evaluadores");
        AssignEvaluators.setName("btnAsignarEva"); // NOI18N
        AssignEvaluators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignEvaluatorsActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Exit.setText("Salir");
        Exit.setName("btnExit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PreProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssignEvaluators)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(PreProjects)
                .addGap(46, 46, 46)
                .addComponent(AssignEvaluators)
                .addGap(41, 41, 41)
                .addComponent(Exit)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AssignEvaluatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignEvaluatorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignEvaluatorsActionPerformed

    public JButton getAssignEvaluators() {
        return AssignEvaluators;
    }

    public JButton getExit() {
        return Exit;
    }

    public JButton getPreProjects() {
        return PreProjects;
    }
    
    public JButton[] getButtons(){
        return new JButton[]{AssignEvaluators, Exit, PreProjects};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignEvaluators;
    private javax.swing.JButton Exit;
    private javax.swing.JButton PreProjects;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
